### ISSUE TITLE
Add a PlanarSurface To RenderMesh method

### ISSUE THREAD

**Issue by al-fisher** [BHoM/TriangleNet_Toolkit#22]
#### Description:

In support of the mesh representation work being carried out (see https://github.com/BHoM/BHoM_Engine/issues/1694) proposing leveraging our DelaunayTriangulate method in order to create a `RenderMesh` from a Planar Surface

This would mean a new method which is potentially injected into the Graphics_Engine along with the other proposed geometry primitive methods which:

1. Takes a `PlanarSurface` as Input

2. Converts the Boundary and Internal Curves to Polylines
   Calls the DelaunayTriangulate method
   Converts the List of closed Polylines returned to a RenderMesh

3. Returns the `RenderMesh`

![image](https://user-images.githubusercontent.com/15924573/80500622-542b1300-8966-11ea-8848-f09c7c746a0f.png)

**Comment by alelom** [comment]
Closed by #27.
